### ISSUE TITLE
Search path error

### ISSUE THREAD

**Issue by kailaw138** [Zhang-Yusong/MSItoolbox#1]
I encounter error on running MSItoolbox:

![Capture](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/05c2ef53-c88b-4540-9c26-6faeedc20286)

I searched the web for some possible solutions and found the following:

●	One possible cause of the error is that you have a cloud synchronization service (such as Dropbox) running in the background, which may lock some files while the compiler is trying to access them. To fix this, you can try to stop the cloud sync service and compile the code again (https://www.mathworks.com/matlabcentral/answers/421804-why-does-matlab-compiler-give-an-error-during-packaging).
●	Another possible cause of the error is that you have set the DefaultAxesCreateFcn in MATLAB to be 'disableDefaultInteractivity (gca)', which is not recommended and may create an extra regular axes in your app. To fix this, you can delete the extra axes, and change the DefaultAxesCreateFcn to use a function handle instead, like this: set (groot, 'defaultAxesCreateFcn', @ (ax,~) disableDefaultInteractivity (ax))(https://www.mathworks.com/matlabcentral/answers/653383-app-designer-matlab-2020b-does-not-open-mlapp-file).
●	If none of the above solutions work, you can also try to lower or disable the compiler optimization level, delete all files generated by the previous compilation, increase the Java Heap space, or use a different or compatible compiler (https://www.mathworks.com/help/rtw/ug/troubleshoot-compiler-issues.html).

Could you please update, and share your manuscript related to MSItoolbox.

**Comment by Zhang-Yusong** [comment]
Dear Dr Law,

Thanks for your feedback

Which file did you encounter this problem with? Run the compiler or the
.mlapp file？
According to the results, it is these two lines of code that cause the
operation to fail:

%%
ilep-pwd;
addpath(genpath(filep));
%%

Their function is to add the file path to the setting path of Matlab.
The error may be caused by a mismatch in compiler versions. You can try to
uninstall the current MATLAB compiler and install version
"MATLAB_Runtime_R2020b win64"(
https://ww2.mathworks.cn/products/compiler/matlab-runtime.html)

If the problem persists, you can contact me again.


Zhang Yusong

Dr Law ***@***.***> 于2023年12月14日周四 18:30写道：

**Comment by Zhang-Yusong** [comment]
Thanks for your feedback

Which file did you encounter this problem with? Run the compiler or the .mlapp file？
According to the results, it is these two lines of code that cause the operation to fail:

%%
ilep-pwd;
addpath(genpath(filep));
%%

Their function is to add the file path to the setting path of Matlab.
The error may be caused by a mismatch in compiler versions. You can try to uninstall the current MATLAB compiler and install version "MATLAB_Runtime_R2020b win64"(https://ww2.mathworks.cn/products/compiler/matlab-runtime.html)

If the problem persists, you can contact me again.

**Comment by kailaw138** [comment]
Thank you again for your reply.

I was running the exe file (the compiler file) with matlab runtime 2020b (v9.9).

I have not tested the .mlapp file, which needs a full version of matlab installed. I am going to try that later.

However, it would be better if you could fix the compiler.

**Comment by Zhang-Yusong** [comment]
Thank you again for your feedback.
I have uploaded the updated code to GitHub. Please download the latest
version of the code and run it again. I look forward to your feedback.

Dr Law ***@***.***> 于2023年12月26日周二 19:26写道：

**Comment by kailaw138** [comment]
Thank you for your support. Herewith my test results... of the updated version 

As far as the compiler, I still encountered the same error on running the exe file...

![11111](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/a52ba4f5-9b47-43bc-b0ce-b553b4b55493)

On running the .mlapp file in matlab 2022b, while the app loads, but again, errors after errors... 

![22222](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/d984f34d-dbad-4b50-9aee-9ea67188e934)

![33333](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/710921bf-6ffa-497b-ab37-8dc5d1a4be3e)

![Capture](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/b1a0e877-eeb1-4874-b443-ea438d0bc19d)

(also tested on matlab 2023a - does not work at all)

**Comment by Zhang-Yusong** [comment]
According to the information in your screenshot, there may be a problem
with the path of the toolbox.
You can try to change the storage path of the toolbox (for example
"F:/MSiToolbox") but do not put it in the Matlab folder.

Dr Law ***@***.***> 于2024年1月2日周二 09:37写道：

**Comment by kailaw138** [comment]
Thank you for your reply. Here my test results...

After relocating the folder to F:/, the mlapp does run in matlab (but the exe file still could not run with matlab runtime), 

1. clustering was fine:

![3 Silhouette score](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/9c463bd9-0a27-4ad8-b75a-d8fec3eb0d0d)
![4 Elbow method](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/2aff2294-7e0d-4ad2-a317-bd9cdcd97271)
![5 tSNE_K-mean](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/66974606-36a6-45f0-b246-3cd036080cc6)

2. but MCR could only get as far as (similar to Fig 7c and 8b of the paper):

![7 estimate PCs with SVD](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/82b97b05-1d9b-414d-b122-e71e2d390ad1)

![MCR](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/ae2180ce-1b0c-46ec-8125-037bcfe6ab76)

and then fell into a forever loop and could not generate anything similar to Fig 9 or 10.

4. Runing ROI (on loading the data) was also extremely slow (took 12 hours to complete), and the app used only a single thread, despite the updated version using Parallel Computing Toolbox.

the previous mlapp release was a lot faster.

**Comment by Zhang-Yusong** [comment]
Thank you very much for your testing and feedback.
Here are some suggestions based on your feedback...

1. Matlab runtime:
At present, I cannot determine the specific reason why the .exe file cannot
run. Still, after my testing, after MATLAB Runtime is correctly installed
on multiple computers, the .exe file can run normally.

2. MCR:
When the interface of Figure 8a of the paper appears, click the "Image"
button and it will jump to the interface of Figure 9a.
"MCR Bands" evaluate rotational ambiguity in multivariate curve resolution.
This function consumes a lot of time and can be ignored for the time being.

3. ROI：
The default parameters of the previous version are different from the
current version, causing you to feel that the old version is faster. Still,
under the same parameters, the current version should be faster.
Therefore, to shorten the ROI running time, you can modify the parameters
of the ROI interface. The paper describes how to set appropriate parameters.


Dr Law ***@***.***> 于2024年1月5日周五 16:23写道：

**Comment by kailaw138** [comment]
Thank for your response.

Matlab runtime is properly installed:

![runtime](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/bb1650d5-4839-48d3-8a5b-0ddc7ad2793c)

MSItoolbox is located in F:/

![toolbox](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/70585c6e-66d3-4b9a-991c-ff8e33965645)

However, on clicking the exe file, it gives me an error message:

![error](https://github.com/Zhang-Yusong/MSItoolbox/assets/119678591/c48d6182-02ca-47f8-9c13-428c200311bc)

On consulting Copilot, it says... 

The reason of this error is due to the use of functions like "addpath", "rmpath", "path", or "matlabpath" in your code. One possible solution is to use the uigetdir function to let the user choose a directory, and then use the dir function to get the list of files in that directory

please see:
[Modifying the search path is not supported by matlab compiler - MATLAB Answers - MATLAB Central (mathworks.com)](https://www.mathworks.com/matlabcentral/answers/1786755-modifying-the-search-path-is-not-supported-by-matlab-compiler)
[application compiler - change search path - MATLAB Answers - MATLAB Central (mathworks.com)](https://www.mathworks.com/matlabcentral/answers/589804-application-compiler-change-search-path)

**Comment by Zhang-Yusong** [comment]
Thanks for your feedback.
I modified it and uploaded a new .exe file.
You can try it again.

Dr Law ***@***.***> 于2024年1月8日周一 09:53写道：
